# DATABASE
spring:
  datasource:
    url: jdbc:postgresql://ls-623fd089fc4b50a043fb2dcbbbba14a51b199bb5.ch4wiamm0eis.ap-northeast-2.rds.amazonaws.com:5432/sbb
    driver-class-name: org.postgresql.Driver
    username: dbmasteruser
    password:

# JPA
jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
      show_sql: true
  hibernate:
    ddl-auto: update

# logging
logging:
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 100MB
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
  file:
    name: logs/sbb.log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,Asia/Seoul
